### ISSUE TITLE
handle match-case using a function argument

### ISSUE THREAD

**Issue by buchs** [charliermarsh/ruff#2671] opened 2023-02-08 22:48 UTC
I saw another issue about documenting a work-around for match/case. I am not sure if that is still relevant.

minimal snippet:

$ cat ruff.py
def f(arga):
   match arga:
      case 'hello':
         print('you passed hello')

import sys
f(sys.argv[1])

Command: `ruff check ruff.py`

No ruff settings (no pyproject.toml).

$ ruff --version
ruff 0.0.243

Error:

$ ruff check ruff.py
error: Failed to parse ruff.py: invalid syntax. Got unexpected token 'arga' at line 2 column 10
ruff.py:2:11: E999 SyntaxError: invalid syntax. Got unexpected token 'arga'

**Comment by buchs** [comment] 2023-02-08 22:48
And, thanks for working on and producing ruff.

**Comment by ngnpope** [comment] 2023-02-08 23:06
Duplicate of #282.

**Comment by charliermarsh** [comment] 2023-02-08 23:06
Thanks for filing! Closing for now as it's being tracked elsewhere.

**Closed by charliermarsh** 2023-02-08 23:06 UTC

**Comment by charliermarsh** [comment] 2023-02-22 00:04
Fixed as of v0.0.250.
