### ISSUE TITLE
`ruff` badge

### ISSUE THREAD

**Issue by matteosantama** [charliermarsh/ruff#1535] opened 2023-01-01 19:45 UTC
A nice wish-list item is a `ruff` badge that other projects can display in their `README.md`, similar to how `mypy`, `black`,  and `isort` have badges (see the badges on [this](https://github.com/matteosantama/dantzig) repo).

**Comment by charliermarsh** [comment] 2023-01-01 21:38
I do want to do this... I'm not sure what it takes exactly.

Just closing as a duplicate of #989.

**Closed by charliermarsh** 2023-01-01 21:38 UTC

**Comment by charliermarsh** [comment] 2023-01-06 04:01
We added a badge!

[![Ruff](https://img.shields.io/endpoint?url=https://raw.githubusercontent.com/charliermarsh/ruff/main/assets/badge/v0.json)](https://github.com/charliermarsh/ruff)
