### ISSUE TITLE
let some rules not cause an error exit code

### ISSUE THREAD

**Issue by spaceone** [charliermarsh/ruff#2349] opened 2023-01-30 11:42 UTC
`ruff` has many rules and i would like to let most of the rules be checked.
we have a repository wide configuration and a pre-commit hook.

As the code base is grown over the years we have many style violation for specific rules (e.g. `RET50{5,6,7,8}` or `SIM`, which are currently also not autofixable) and we don't have them time to do it manually currently.
but the rules would make sense for our code base.

So I would like to have them visible for the developers, so that they see that there is an issue (which they might fix then as well) but `ruff` should not exit with an exit code =! 0 for them, as this would e.g. block the pre-commit hook.

→ A new config option could provide a list of rules which still get reported but don't cause an error.

**Comment by ngnpope** [comment] 2023-01-30 11:52
I like this idea. This is essentially requesting to treat certain rules as a warning rather than an error, right?

A few thoughts then:

- What should the configuration option be? Maybe `warn-only = ["…", …]`?
- The summary should show `Found … errors and … warnings.`
- Colored output should have codes highlighted in yellow for warnings
- What about `--format=grouped` output? Would be nice for errors to be grouped together, then warnings...
  - But then maybe we want `--format=grouped,severity`?

**Comment by charliermarsh** [comment] 2023-01-30 12:10
👍 We plan to support severity levels for rules (see also #1256), which should solve this.

Once that's done, you should be able to mark rules as warnings or errors (presumedly everything will be an error by default, but TBD). And then you should be able to use "warning" and "error" to select rules (e.g., `ruff --select warnings`, API TBD). And they'd show up similarly to how @ngnpope has described in the CLI output.

**Comment by charliermarsh** [comment] 2023-01-30 17:15
Just gonna close as a duplicate of #1256.

**Closed by charliermarsh** 2023-01-30 17:15 UTC
