### ISSUE TITLE
Request: `RET504` autofix

### ISSUE THREAD

**Issue by jamesbraza** [charliermarsh/ruff#4586] opened 2023-05-22 17:33 UTC
It seems like `RET504` should be autofixable, but as of `ruff==0.0.269`, it's not autofixable.

```python
def foo() -> int:
    ret = 5
    return ret
```

```bash
> ruff --select=RET504 a.py
a.py:3:12: RET504 Unnecessary variable assignment before `return` statement
```

```python
def foo() -> int:
    return 5
```

The request is simple: adding an autofix rule for `RET504` to `ruff`

---

**Motivation**

I want to enable `RET504` in a monorepo, but it requires 200+ manual fixes 🥲

**Comment by charliermarsh** [comment] 2023-05-22 17:37
Duplicate of #2263 :)

**Closed by charliermarsh** 2023-05-22 17:37 UTC

**Comment by jamesbraza** [comment] 2023-05-22 17:42
I actually searched for a prior request for this, I must have been blind 😄
