### ISSUE TITLE
E712 : Wrong fix suggested in presence of `numpy.bool_`

### ISSUE THREAD

**Issue by kesinger-idexx** [charliermarsh/ruff#4356] opened 2023-05-10 18:36 UTC
Using ruff 0.0.265.

In this code, the two if-blocks are NOT equivalent:

    def f(x):
        # x is a np.ndarray with at least 2 dimensions
        return x[0, 0] > 0

    x = np.eye(2)
    a = f(x)
    if a == True:
        print("a==True")
    if a is True:
        print("a is True")
        assert(False)

What's going on is `type(a)==numpy.bool_` which can be compared to True/False via `==` but it is not referentially the same.

**Comment by madkinsz** [comment] 2023-05-10 18:40
Duplicate of https://github.com/charliermarsh/ruff/issues/2443

**Closed** 2023-05-10 20:12 UTC
