### ISSUE TITLE
TCH002 autofix

### ISSUE THREAD

**Issue by Olegt0rr** [charliermarsh/ruff#3120] opened 2023-02-22 12:16 UTC
It would be great to implement the ability to automatically fix the TCH002 error so that the import is automatically placed in the TYPE_CHECKING block.

It's so boring to fix it manually:
1. Ensure that `TYPE_CHECKING` imported from `typing`
2. Ensure that block `if TYPE_CHECKING:` exists
3. Move import to the block

**Comment by charliermarsh** [comment] 2023-02-22 19:31
Agreed. Just gonna close this as a duplicate of #2329.

**Closed by charliermarsh** 2023-02-22 19:31 UTC

**Comment by Olegt0rr** [comment] 2023-02-23 13:12
Oh, thanks!
It's would be nice to add rule codes to issues to make it more searchable
