### ISSUE TITLE
How does ruff compare to pylint?

### ISSUE THREAD

**Issue by olivier-lacroix** [charliermarsh/ruff#689] opened 2022-11-12 00:35 UTC
Hello there,

I understand ruff’s primary point of comparison is flake8, but I am curious to know how it compares with pylint. This would likely help people considering migrating to ruff from pylint.

And maybe some inspiration could also be taken from pylint feature-wise? For instance, the use of “dev readable error codes” makes things a lot clearer when reading code.

**Comment by LefterisJP** [comment] 2022-11-16 13:07
Pylint does a lot of AST analysis and has lots of modules and a modular system.
It's pretty cool. I have written pylint modules in the past.

The problem is that it is excruciatingly slow.

If ruff could go towards that and stay as fast as it is ... oh boy I would be in love.

**Comment by hmc-cs-mdrissi** [comment] 2022-11-20 01:59
Pylint has a very long list of rules. I currently use pylint but mainly stick to W/E/F rules as they catch most of interesting issues in my codebase. The more stylistic rules like formatting/variable naming/docstrings I value less.

I'd find most value in Error [rules](http://pylint-messages.wikidot.com/all-codes) here. Almost all of them I enable, they've caught a number of bugs, and find false positive rate pretty low. One caveat is some rules I do rely on exception lists based on known problematic modules. As an example generated-members is useful way of dealing with modules/classes that have many dynamically defined attributes and static analysis would otherwise produce a lot of false positives.

**Comment by charliermarsh** [comment] 2022-11-30 03:05
# Fatal

- [] `astroid-error` / `F0002`
- [] `config-parse-error` / `F0011`
- [] `fatal` / `F0001`
- [] `method-check-failed` / `F0202`
- [] `parse-error` / `F0010`

# Error

- [] `abstract-class-instantiated` / `E0110`
- [] `access-member-before-definition` / `E0203`
- [] `assigning-non-slot` / `E0237`
- [] `assignment-from-no-return` / `E1111`
- [] `assignment-from-none` / `E1128`
- [] `await-outside-async` / `E1142`
- [] `bad-configuration-section` / `E0014`
- [] `bad-except-order` / `E0701`
- [] `bad-exception-cause` / `E0705`
- [] `bad-format-character` / `E1300`
- [] `bad-plugin-value` / `E0013`
- [] `bad-reversed-sequence` / `E0111`
- [] `bad-str-strip-call` / `E1310`
- [] `bad-string-format-type` / `E1307`
- [] `bad-super-call` / `E1003`
- [] `bidirectional-unicode` / `E2502`
- [] `broken-collections-callable` / `E6005`
- [] `broken-noreturn` / `E6004`
- [] `catching-non-exception` / `E0712`
- [] `class-variable-slots-conflict` / `E0242`
- [] `continue-in-finally` / `E0116`
- [] `dict-iter-missing-items` / `E1141`
- [] `duplicate-argument-name` / `E0108`
- [] `duplicate-bases` / `E0241`
- [] `format-needs-mapping` / `E1303`
- [] `function-redefined` / `E0102`
- [] `import-error` / `E0401`
- [] `inconsistent-mro` / `E0240`
- [] `inherit-non-class` / `E0239`
- [] `init-is-generator` / `E0100`
- [] `invalid-all-format` / `E0605`
- [] `invalid-all-object` / `E0604`
- [] `invalid-bool-returned` / `E0304`
- [] `invalid-bytes-returned` / `E0308`
- [] `invalid-character-backspace` / `E2510`
- [] `invalid-character-carriage-return` / `E2511`
- [] `invalid-character-esc` / `E2513`
- [] `invalid-character-nul` / `E2514`
- [] `invalid-character-sub` / `E2512`
- [] `invalid-character-zero-width-space` / `E2515`
- [] `invalid-class-object` / `E0243`
- [] `invalid-enum-extension` / `E0244`
- [] `invalid-envvar-value` / `E1507`
- [] `invalid-format-returned` / `E0311`
- [] `invalid-getnewargs-ex-returned` / `E0313`
- [] `invalid-getnewargs-returned` / `E0312`
- [] `invalid-hash-returned` / `E0309`
- [] `invalid-index-returned` / `E0305`
- [] `invalid-length-hint-returned` / `E0310`
- [] `invalid-length-returned` / `E0303`
- [] `invalid-metaclass` / `E1139`
- [] `invalid-repr-returned` / `E0306`
- [] `invalid-sequence-index` / `E1126`
- [] `invalid-slice-index` / `E1127`
- [] `invalid-slice-step` / `E1144`
- [] `invalid-slots` / `E0238`
- [] `invalid-slots-object` / `E0236`
- [] `invalid-star-assignment-target` / `E0113`
- [] `invalid-str-returned` / `E0307`
- [] `invalid-unary-operand-type` / `E1130`
- [] `invalid-unicode-codec` / `E2501`
- [] `logging-format-truncated` / `E1201`
- [] `logging-too-few-args` / `E1206`
- [] `logging-too-many-args` / `E1205`
- [] `logging-unsupported-format` / `E1200`
- [] `method-hidden` / `E0202`
- [] `misplaced-bare-raise` / `E0704`
- [] `misplaced-format-function` / `E0119`
- [] `missing-format-string-key` / `E1304`
- [] `missing-kwoa` / `E1125`
- [] `mixed-format-string` / `E1302`
- [] `modified-iterating-dict` / `E4702`
- [] `modified-iterating-set` / `E4703`
- [] `no-member` / `E1101`
- [] `no-method-argument` / `E0211`
- [] `no-name-in-module` / `E0611`
- [] `no-self-argument` / `E0213`
- [] `no-value-for-parameter` / `E1120`
- [] `non-iterator-returned` / `E0301`
- [] `nonexistent-operator` / `E0107`
- [] `nonlocal-and-global` / `E0115`
- [] `nonlocal-without-binding` / `E0117`
- [] `not-a-mapping` / `E1134`
- [] `not-an-iterable` / `E1133`
- [] `not-async-context-manager` / `E1701`
- [] `not-callable` / `E1102`
- [] `not-context-manager` / `E1129`
- [] `not-in-loop` / `E0103`
- [] `notimplemented-raised` / `E0711`
- [] `potential-index-error` / `E0643`
- [] `raising-bad-type` / `E0702`
- [] `raising-non-exception` / `E0710`
- [] `redundant-keyword-arg` / `E1124`
- [] `relative-beyond-top-level` / `E0402`
- [] `repeated-keyword` / `E1132`
- [] `return-arg-in-generator` / `E0106`
- [] `return-in-init` / `E0101`
- [] `return-outside-function` / `E0104`
- [] `singledispatch-method` / `E1519`
- [] `singledispatchmethod-function` / `E1520`
- [] `star-needs-assignment-target` / `E0114`
- [] `syntax-error` / `E0001`
- [] `too-few-format-args` / `E1306`
- [] `too-many-format-args` / `E1305`
- [] `too-many-function-args` / `E1121`
- [] `too-many-star-expressions` / `E0112`
- [] `truncated-format-string` / `E1301`
- [] `undefined-all-variable` / `E0603`
- [] `undefined-variable` / `E0602`
- [] `unexpected-keyword-arg` / `E1123`
- [] `unexpected-special-method-signature` / `E0302`
- [] `unhashable-member` / `E1143`
- [] `unpacking-non-sequence` / `E0633`
- [] `unrecognized-inline-option` / `E0011`
- [] `unrecognized-option` / `E0015`
- [] `unsubscriptable-object` / `E1136`
- [] `unsupported-assignment-operation` / `E1137`
- [] `unsupported-binary-operation` / `E1131`
- [] `unsupported-delete-operation` / `E1138`
- [] `unsupported-membership-test` / `E1135`
- [] `used-before-assignment` / `E0601`
- [] `used-prior-global-declaration` / `E0118`
- [] `yield-inside-async-function` / `E1700`
- [] `yield-outside-function` / `E0105`

# Warning

- [] `abstract-method` / `W0223`
- [] `anomalous-backslash-in-string` / `W1401`
- [] `anomalous-unicode-escape-in-string` / `W1402`
- [] `arguments-differ` / `W0221`
- [] `arguments-out-of-order` / `W1114`
- [] `arguments-renamed` / `W0237`
- [] `assert-on-string-literal` / `W0129`
- [] `assert-on-tuple` / `W0199`
- [] `attribute-defined-outside-init` / `W0201`
- [] `bad-builtin` / `W0141`
- [] `bad-dunder-name` / `W3201`
- [] `bad-format-string` / `W1302`
- [] `bad-format-string-key` / `W1300`
- [] `bad-indentation` / `W0311`
- [] `bad-open-mode` / `W1501`
- [] `bad-staticmethod-argument` / `W0211`
- [] `bad-thread-instantiation` / `W1506`
- [] `bare-except` / `W0702`
- [] `binary-op-exception` / `W0711`
- [] `boolean-datetime` / `W1502`
- [] `broad-exception-caught` / `W0718`
- [] `broad-exception-raised` / `W0719`
- [] `cell-var-from-loop` / `W0640`
- [] `comparison-with-callable` / `W0143`
- [] `confusing-with-statement` / `W0124`
- [] `consider-ternary-expression` / `W0160`
- [] `dangerous-default-value` / `W0102`
- [] `deprecated-argument` / `W4903`
- [] `deprecated-class` / `W4904`
- [] `deprecated-decorator` / `W4905`
- [] `deprecated-method` / `W4902`
- [] `deprecated-module` / `W4901`
- [] `deprecated-typing-alias` / `W6001`
- [] `differing-param-doc` / `W9017`
- [] `differing-type-doc` / `W9018`
- [] `duplicate-except` / `W0705`
- [] `duplicate-key` / `W0109`
- [] `duplicate-string-formatting-argument` / `W1308`
- [] `duplicate-value` / `W0130`
- [] `eq-without-hash` / `W1641`
- [] `eval-used` / `W0123`
- [] `exec-used` / `W0122`
- [] `expression-not-assigned` / `W0106`
- [] `f-string-without-interpolation` / `W1309`
- [] `fixme` / `W0511`
- [] `forgotten-debug-statement` / `W1515`
- [] `format-combined-specification` / `W1305`
- [] `format-string-without-interpolation` / `W1310`
- [] `global-at-module-level` / `W0604`
- [] `global-statement` / `W0603`
- [] `global-variable-not-assigned` / `W0602`
- [] `global-variable-undefined` / `W0601`
- [] `implicit-str-concat` / `W1404`
- [] `import-self` / `W0406`
- [] `inconsistent-quotes` / `W1405`
- [] `invalid-envvar-default` / `W1508`
- [] `invalid-format-index` / `W1307`
- [] `invalid-overridden-method` / `W0236`
- [] `isinstance-second-argument-not-valid-type` / `W1116`
- [] `keyword-arg-before-vararg` / `W1113`
- [] `logging-format-interpolation` / `W1202`
- [] `logging-fstring-interpolation` / `W1203`
- [] `logging-not-lazy` / `W1201`
- [] `lost-exception` / `W0150`
- [] `method-cache-max-size-none` / `W1518`
- [] `misplaced-future` / `W0410`
- [] `missing-any-param-doc` / `W9021`
- [] `missing-format-argument-key` / `W1303`
- [] `missing-format-attribute` / `W1306`
- [] `missing-param-doc` / `W9015`
- [] `missing-parentheses-for-call-in-test` / `W0126`
- [] `missing-raises-doc` / `W9006`
- [] `missing-return-doc` / `W9011`
- [] `missing-return-type-doc` / `W9012`
- [] `missing-timeout` / `W3101`
- [] `missing-type-doc` / `W9016`
- [] `missing-yield-doc` / `W9013`
- [] `missing-yield-type-doc` / `W9014`
- [] `modified-iterating-list` / `W4701`
- [] `multiple-constructor-doc` / `W9005`
- [] `named-expr-without-context` / `W0131`
- [] `nan-comparison` / `W0177`
- [] `nested-min-max` / `W3301`
- [] `non-ascii-file-name` / `W2402`
- [] `non-parent-init-called` / `W0233`
- [] `non-str-assignment-to-dunder-name` / `W1115`
- [] `overlapping-except` / `W0714`
- [] `overridden-final-method` / `W0239`
- [] `pointless-statement` / `W0104`
- [] `pointless-string-statement` / `W0105`
- [] `possibly-unused-variable` / `W0641`
- [] `preferred-module` / `W0407`
- [] `protected-access` / `W0212`
- [] `raise-missing-from` / `W0707`
- [] `raising-format-tuple` / `W0715`
- [] `redeclared-assigned-name` / `W0128`
- [] `redefined-builtin` / `W0622`
- [] `redefined-loop-name` / `W2901`
- [] `redefined-outer-name` / `W0621`
- [] `redefined-slots-in-subclass` / `W0244`
- [] `redundant-returns-doc` / `W9008`
- [] `redundant-u-string-prefix` / `W1406`
- [] `redundant-unittest-assert` / `W1503`
- [] `redundant-yields-doc` / `W9010`
- [] `reimported` / `W0404`
- [] `self-assigning-variable` / `W0127`
- [] `self-cls-assignment` / `W0642`
- [] `shallow-copy-environ` / `W1507`
- [] `signature-differs` / `W0222`
- [] `subclassed-final-class` / `W0240`
- [] `subprocess-popen-preexec-fn` / `W1509`
- [] `subprocess-run-check` / `W1510`
- [] `super-init-not-called` / `W0231`
- [] `super-without-brackets` / `W0245`
- [] `too-many-try-statements` / `W0717`
- [] `try-except-raise` / `W0706`
- [] `unbalanced-dict-unpacking` / `W0644`
- [] `unbalanced-tuple-unpacking` / `W0632`
- [] `undefined-loop-variable` / `W0631`
- [] `unknown-option-value` / `W0012`
- [] `unnecessary-ellipsis` / `W2301`
- [] `unnecessary-lambda` / `W0108`
- [] `unnecessary-pass` / `W0107`
- [] `unnecessary-semicolon` / `W0301`
- [] `unreachable` / `W0101`
- [] `unspecified-encoding` / `W1514`
- [] `unused-argument` / `W0613`
- [] `unused-format-string-argument` / `W1304`
- [] `unused-format-string-key` / `W1301`
- [] `unused-import` / `W0611`
- [] `unused-private-member` / `W0238`
- [] `unused-variable` / `W0612`
- [] `unused-wildcard-import` / `W0614`
- [] `useless-else-on-loop` / `W0120`
- [] `useless-param-doc` / `W9019`
- [] `useless-parent-delegation` / `W0246`
- [] `useless-type-doc` / `W9020`
- [] `useless-with-lock` / `W2101`
- [] `using-constant-test` / `W0125`
- [] `using-f-string-in-unsupported-version` / `W2601`
- [] `using-final-decorator-in-unsupported-version` / `W2602`
- [] `while-used` / `W0149`
- [] `wildcard-import` / `W0401`
- [] `wrong-exception-operation` / `W0716`

# Convention

- [] `bad-classmethod-argument` / `C0202`
- [] `bad-docstring-quotes` / `C0198`
- [] `bad-file-encoding` / `C2503`
- [] `bad-mcs-classmethod-argument` / `C0204`
- [] `bad-mcs-method-argument` / `C0203`
- [] `compare-to-empty-string` / `C1901`
- [] `compare-to-zero` / `C2001`
- [] `consider-iterating-dictionary` / `C0201`
- [] `consider-using-any-or-all` / `C0501`
- [] `consider-using-dict-items` / `C0206`
- [] `consider-using-enumerate` / `C0200`
- [] `consider-using-f-string` / `C0209`
- [] `dict-init-mutate` / `C3401`
- [] `disallowed-name` / `C0104`
- [] `docstring-first-line-empty` / `C0199`
- [] `empty-docstring` / `C0112`
- [] `import-outside-toplevel` / `C0415`
- [] `import-private-name` / `C2701`
- [] `invalid-characters-in-docstring` / `C0403`
- [] `invalid-name` / `C0103`
- [] `line-too-long` / `C0301`
- [] `misplaced-comparison-constant` / `C2201`
- [] `missing-class-docstring` / `C0115`
- [] `missing-final-newline` / `C0304`
- [] `missing-function-docstring` / `C0116`
- [] `missing-module-docstring` / `C0114`
- [] `mixed-line-endings` / `C0327`
- [] `multiple-imports` / `C0410`
- [] `multiple-statements` / `C0321`
- [] `non-ascii-module-import` / `C2403`
- [] `non-ascii-name` / `C2401`
- [] `single-string-used-for-slots` / `C0205`
- [] `singleton-comparison` / `C0121`
- [] `superfluous-parens` / `C0325`
- [] `too-many-lines` / `C0302`
- [] `trailing-newlines` / `C0305`
- [] `trailing-whitespace` / `C0303`
- [] `typevar-double-variance` / `C0131`
- [] `typevar-name-incorrect-variance` / `C0105`
- [] `typevar-name-mismatch` / `C0132`
- [] `unexpected-line-ending-format` / `C0328`
- [] `ungrouped-imports` / `C0412`
- [] `unidiomatic-typecheck` / `C0123`
- [] `unnecessary-direct-lambda-call` / `C3002`
- [] `unnecessary-dunder-call` / `C2801`
- [] `unnecessary-lambda-assignment` / `C3001`
- [] `unneeded-not` / `C0113`
- [] `use-implicit-booleaness-not-comparison` / `C1803`
- [] `use-implicit-booleaness-not-len` / `C1802`
- [] `use-maxsplit-arg` / `C0207`
- [] `use-sequence-for-iteration` / `C0208`
- [] `useless-import-alias` / `C0414`
- [] `wrong-import-order` / `C0411`
- [] `wrong-import-position` / `C0413`
- [] `wrong-spelling-in-comment` / `C0401`
- [] `wrong-spelling-in-docstring` / `C0402`

# Refactor

- [] `chained-comparison` / `R1716`
- [] `comparison-of-constants` / `R0133`
- [] `comparison-with-itself` / `R0124`
- [] `condition-evals-to-constant` / `R1727`
- [] `confusing-consecutive-elif` / `R5601`
- [] `consider-alternative-union-syntax` / `R6003`
- [] `consider-merging-isinstance` / `R1701`
- [] `consider-swap-variables` / `R1712`
- [] `consider-using-alias` / `R6002`
- [] `consider-using-assignment-expr` / `R6103`
- [] `consider-using-augmented-assign` / `R6104`
- [] `consider-using-dict-comprehension` / `R1717`
- [] `consider-using-from-import` / `R0402`
- [] `consider-using-generator` / `R1728`
- [] `consider-using-get` / `R1715`
- [] `consider-using-in` / `R1714`
- [] `consider-using-join` / `R1713`
- [] `consider-using-max-builtin` / `R1731`
- [] `consider-using-min-builtin` / `R1730`
- [] `consider-using-namedtuple-or-dataclass` / `R6101`
- [] `consider-using-set-comprehension` / `R1718`
- [] `consider-using-sys-exit` / `R1722`
- [] `consider-using-ternary` / `R1706`
- [] `consider-using-tuple` / `R6102`
- [] `consider-using-with` / `R1732`
- [] `cyclic-import` / `R0401`
- [] `duplicate-code` / `R0801`
- [] `else-if-used` / `R5501`
- [] `empty-comment` / `R2044`
- [] `inconsistent-return-statements` / `R1710`
- [] `literal-comparison` / `R0123`
- [] `magic-value-comparison` / `R2004`
- [] `no-classmethod-decorator` / `R0202`
- [] `no-else-break` / `R1723`
- [] `no-else-continue` / `R1724`
- [] `no-else-raise` / `R1720`
- [] `no-else-return` / `R1705`
- [] `no-self-use` / `R6301`
- [] `no-staticmethod-decorator` / `R0203`
- [] `property-with-parameters` / `R0206`
- [] `redefined-argument-from-local` / `R1704`
- [] `redefined-variable-type` / `R0204`
- [] `simplifiable-condition` / `R1726`
- [] `simplifiable-if-expression` / `R1719`
- [] `simplifiable-if-statement` / `R1703`
- [] `simplify-boolean-expression` / `R1709`
- [] `stop-iteration-return` / `R1708`
- [] `super-with-arguments` / `R1725`
- [] `too-complex` / `R1260`
- [] `too-few-public-methods` / `R0903`
- [] `too-many-ancestors` / `R0901`
- [] `too-many-arguments` / `R0913`
- [] `too-many-boolean-expressions` / `R0916`
- [] `too-many-branches` / `R0912`
- [] `too-many-instance-attributes` / `R0902`
- [] `too-many-locals` / `R0914`
- [] `too-many-nested-blocks` / `R1702`
- [] `too-many-public-methods` / `R0904`
- [] `too-many-return-statements` / `R0911`
- [] `too-many-statements` / `R0915`
- [] `trailing-comma-tuple` / `R1707`
- [] `unnecessary-comprehension` / `R1721`
- [] `unnecessary-dict-index-lookup` / `R1733`
- [] `unnecessary-list-index-lookup` / `R1736`
- [] `use-a-generator` / `R1729`
- [] `use-dict-literal` / `R1735`
- [] `use-list-literal` / `R1734`
- [] `use-set-for-membership` / `R6201`
- [] `useless-object-inheritance` / `R0205`
- [] `useless-option-value` / `R0022`
- [] `useless-return` / `R1711`

# Information

- [] `bad-inline-option` / `I0010`
- [] `c-extension-no-member` / `I1101`
- [] `deprecated-pragma` / `I0022`
- [] `file-ignored` / `I0013`
- [] `locally-disabled` / `I0011`
- [] `raw-checker-failed` / `I0001`
- [] `suppressed-message` / `I0020`
- [] `use-symbolic-message-instead` / `I0023`
- [] `useless-suppression` / `I0021`

**Comment by charliermarsh** [comment] 2022-11-30 03:06
Pylint supports 409 rules to Ruff's 224 rules. I'm gonna go through and see where we're lacking.

**Comment by charliermarsh** [comment] 2022-11-30 03:40
For the sake of simplicity, I'm just gonna ignore the "Fatal" and "Information" categories.

That leaves 395 rules, of which Ruff implements 63 (this is a rough count, since the rules aren't always identical), with 332 unimplemented.

**Comment by charliermarsh** [comment] 2022-11-30 03:42
We should add a bunch of these! I'd probably start with the `E` rules, though there's a lot of low-hanging fruit in the `W` category. I can do one or two to add least add Pylint as a category.

\cc @harupy if you're ever interested in some of these.

**Comment by charliermarsh** [comment] 2022-11-30 04:53
Added to the README here: #969. For clarity, I'm going to close this out in favor of a new issue to track actual work towards improving parity: https://github.com/charliermarsh/ruff/issues/970.

**Closed by charliermarsh** 2022-11-30 04:53 UTC
Labels: documentation, question

**Comment by Pierre-Sassoulas** [comment] 2023-01-16 12:51
(I'm a pylint maintainer). One way to know if it's easy to implement a pylint rule is to check the confidence used when raising a message. If there's no inference (I.E. the check is static and could be done without astroid's inference capability) then the confidence is going to be HIGH in ``add_message``.  For example [``consider-using-any-or-all"`` does not use inference](https://github.com/PyCQA/pylint/blob/aeaa16d4af44abbf263643a63f6df8298802c701/pylint/extensions/for_any_all.py#L57) but some [corner cases of ``use-implicit-booleaness-not-len`` do](https://github.com/PyCQA/pylint/blob/aeaa16d4af44abbf263643a63f6df8298802c701/pylint/checkers/refactoring/implicit_booleaness_checker.py#L123).

 The confidence is not defined everywhere though, this is an ongoing effort.

**Comment by nicois** [comment] 2023-01-16 22:19
Is there any intention of respecting pylint's annotations allowing errors to be disabled for a certain scope?

One impediment to switching over is the large number of pylint annotations which immediately throw errors. e.g. `# pylint: disable=bare-except`. 

If ruff supported more pylint rules this would not be so important, as a single regex replacement over the codebase would allow migration. However in the interim we need to continue to use pylint in pre-commit hooks, but would like to enable ruff in developers' IDEs.

**Comment by charliermarsh** [comment] 2023-01-17 12:53
Yeah this came up in #1203. I'll leave a comment there!

**Comment by Lewiscowles1986** [comment] 2023-09-16 02:44
Unsure if data or noise, but [`R1707`](https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/trailing-comma-tuple.html) would have saved me a headache yesterday

A Change in Pydantic design might also have helped, but pylint catching these is a game-changer for large classes.

<img alt="Screenshot: Visual Studio Code. Shows pylint integration highlighting trailing commas, in a way mypy, black, flake8 and ruff don't seem to" src="https://github.com/astral-sh/ruff/assets/2605791/b8b7288a-e0a7-4c39-9cea-ed51d03cdd67">

The other benefit of pylint for me here is the IDE integration with VSCode. I Still have not made time to check this in my PyCharm, but... yeah, I like pylint for at-least this reason.

**Comment by charliermarsh** [comment] 2023-09-16 03:05
@Lewiscowles1986 - We do support that rule, but it's under a different code: [`trailing-comma-on-bare-tuple`](https://docs.astral.sh/ruff/rules/trailing-comma-on-bare-tuple/), known as COM818.

**Comment by Lewiscowles1986** [comment] 2023-09-16 03:06
Is it on-by-default, and what setup would need to be done to get it to show up via the linked VSCode extension?

**Comment by charliermarsh** [comment] 2023-09-16 03:43
Yeah, you can add `COM818` to your `select` to enable the rule.

**Comment by mistercrunch** [comment] 2024-06-03 23:38
Hey, wondering if the checkbox list above is maintained/up-to-date (?) I'd love to have a full list of rules that I can disable in pylint cause it's very very slow. I'm working on a refactor that touches many python files (50+) and the pylint commit-hook is killing me, like it takes 5+ minutes to run :( . Now that I got a taste of that nice ruff speed I'm hooked.

I'm hoping if I can disable the redundant rules on the pylint side, the engine will run that much faster...

**Comment by charliermarsh** [comment] 2024-06-03 23:59
@mistercrunch - we keep #970 up-to-date, in that we update it whenever we implement a new rule, and then whenever someone comments to point out that a rule is already covered or similar.
