### ISSUE TITLE
C4 should not be remapped to C40, leaves out C41

### ISSUE THREAD

**Issue by onerandomusername** [charliermarsh/ruff#3502] opened 2023-03-14 05:05 UTC
Newest ruff version remaps C4 to C40 but that leaves out C41 of flake8-comphrehensions. https://beta.ruff.rs/docs/rules/#flake8-comprehensions-c4

version: ruff 0.0.255

**Comment by CalumY** [comment] 2023-03-14 07:20
I think this might be a duplicate of #3486, which was fixed by #3488.

**Comment by charliermarsh** [comment] 2023-03-14 14:23
Yup! This has been fixed.

**Closed by charliermarsh** 2023-03-14 14:23 UTC

**Comment by onerandomusername** [comment] 2023-03-15 16:46
Whoops, sorry! I searched for duplicates but hadn't found it, thanks!

**Comment by charliermarsh** [comment] 2023-03-15 16:58
No prob :)
