### ISSUE TITLE
`pep8-naming.ignore-names`: add support for patterns (wildcard)

### ISSUE THREAD

**Issue by saippuakauppias** [charliermarsh/ruff#4708] opened 2023-05-29 20:21 UTC
I think it would be useful to add pattern support to this option, so that you can set:
```
[tool.ruff.pep8-naming]
ignore-names = ["callMethod", "assert*"]
```

This is to avoid processing rule `invalid-function-name (N802)` on functions that are written in unittest and django-style:
- https://docs.python.org/3/library/unittest.html#unittest.TestCase.debug (see table)
- https://github.com/django/django/blob/4.1/django/test/testcases.py#L291 (see methods starts from `assert`)

**Comment by JonathanPlasse** [comment] 2023-05-29 22:52
- Duplicate of #2787.

**Closed** 2023-05-29 23:01 UTC
Labels: configuration
