### ISSUE TITLE
rule explanation should show a code example

### ISSUE THREAD

**Issue by spaceone** [charliermarsh/ruff#2428] opened 2023-01-31 23:24 UTC
Every rule explanation should show show a code example:

e.g.
```diff
$ ruff rule SIM210
if-expr-with-true-false

Code: SIM210 (flake8-simplify)

Autofix is always available.

Message formats:

* Use `bool({expr})` instead of `True if {expr} else False`

Example:
-a = True if b else False
+a = bool(b)
```

**Comment by not-my-profile** [comment] 2023-02-01 03:23
I agree. I'd consider this a duplicate of #1467.

**Closed** 2023-02-01 04:54 UTC
