### ISSUE TITLE
Add Darglint Checks

### ISSUE THREAD

**Issue by rbebb** [charliermarsh/ruff#2459] opened 2023-02-02 00:11 UTC
It would be amazing if [darglint](https://github.com/terrencepreilly/darglint)’s  checks/rules were added to ruff. darglint’s GitHub repo was archived at the end of last year and it’s also quite slow.

**Comment by edgarrmondragon** [comment] 2023-02-02 00:14
Duplicate of https://github.com/charliermarsh/ruff/issues/458

**Comment by charliermarsh** [comment] 2023-02-02 00:16
Everyone wants darglint :joy:

**Closed** 2023-02-02 00:16 UTC

**Comment by rbebb** [comment] 2023-02-02 00:19
@charliermarsh Haha I’m sure! Sorry that I didn’t come across that ticket before making a new one. I appreciate you linking the original ticket!
