### ISSUE TITLE
`Removes quotes from annotations` removes quotes from literal values

### ISSUE THREAD

**Issue by Czaki** [charliermarsh/ruff#2613] opened 2023-02-06 22:51 UTC
It looks like  #2431 also removes quotes from literal values in type annotation 

In general, when bump ruff from 0.0.237 to 0.0.242 the following change is generated by ruff: 

```
Literal["x86_64", "arm64"]
```
to 
```
Literal[x86_64, arm64]
```
cibuilwheel PR with visible problem 

https://github.com/pypa/cibuildwheel/pull/1412

The change, when force revert changes

[pypa/cibuildwheel@`923fd3c` (#1412)](https://github.com/pypa/cibuildwheel/pull/1412/commits/923fd3c493f26461cd22a85ce736bb7cd54bc273)

And log from ruff: 

https://results.pre-commit.ci/run/github/85508223/1675723555.oUgkXTipRmOlnOPISWV1OA

ruff configuration https://github.com/pypa/cibuildwheel/blob/e42277a69204ccfae9a1f4ae3b574eaa54109925/pyproject.toml#L120

**Comment by charliermarsh** [comment] 2023-02-06 23:02
Thank you, I'll fix this tonight and cut a new release.

**Comment by henryiii** [comment] 2023-02-06 23:04
Breaking pypa/build too: https://github.com/pypa/build/pull/576/files

```diff
- PathType = Union[str, 'os.PathLike[str]']
+ PathType = Union[str, os.PathLike[str]]

- _TProjectBuilder = TypeVar('_TProjectBuilder', bound='ProjectBuilder')
+ _TProjectBuilder = TypeVar('_TProjectBuilder', bound=ProjectBuilder)
```

These are both broken. `os.PathLike[str]` is not valid on Python 3.7 (and it's not an annotation). TypeVar can't have the quotes removed, the thing it's bound to doesn't exist yet.

**Comment by henryiii** [comment] 2023-02-06 23:07
Also, I'd really love for a way to see see fixed operaitons too. I have no idea what rules were applied when things are "fixed". Maybe there's a flag I missed?

**Comment by charliermarsh** [comment] 2023-02-06 23:07
In the `Literal` case, the issue is that you're accessing `Literal` from a module that isn't `typing` or `typing_extensions`.

For example, this doesn't raise an error:

```py
from __future__ import annotations

from typing import Literal

x: Literal["x86_64", "arm64"]
```

But this does:

```py
from __future__ import annotations

from .typing import Literal

x: Literal["x86_64", "arm64"]
```

We use [`typing-modules`](https://github.com/charliermarsh/ruff#typing-modules) to fix this, but it doesn't support relative imports right now.

**Comment by charliermarsh** [comment] 2023-02-06 23:08
> Also, I'd really love for a way to see see fixed operaitons too. I have no idea what rules were applied when things are "fixed". Maybe there's a flag I missed?

There's a `--diff` flag -- is that along the lines of what you're describing?

**Comment by charliermarsh** [comment] 2023-02-06 23:15
The issues that @henryiii raised are fixed in #2614.

**Comment by charliermarsh** [comment] 2023-02-06 23:16
I can add support for relative import paths with `typing-modules` to fix the issue @Czaki raised. (I'm actually surprised that hasn't bitten you already prior to this lint rule!)

**Comment by henryiii** [comment] 2023-02-06 23:16
I can see a diff of what changed, I just can't see the list of rules that were applied to make those changes. For example, if I make a fixable change to a Ruby file and run rubocop:

```
Inspecting 16 files
....C...........

Offenses:

_plugins/checkproj.rb:36:7: C: [Corrected] Style/RedundantReturn: Redundant return detected.
      return @people ||= people_gen
      ^^^^^^

16 files inspected, 1 offense detected, 1 offense corrected
```

I can see exactly what rules were applied in the fixes.

**Comment by henryiii** [comment] 2023-02-06 23:18
The typgin modules issue has bit before, it's https://github.com/charliermarsh/ruff/issues/2005.

**Comment by charliermarsh** [comment] 2023-02-06 23:45
Gonna try and fix that tonight.

**Closed** 2023-02-07 00:51 UTC
Labels: bug

**Comment by Czaki** [comment] 2023-02-07 19:28
Thanks for the really fast action :) :heart:
