### ISSUE TITLE
Match-case causes syntax errors

### ISSUE THREAD

**Issue by nefrob** [charliermarsh/ruff#2377] opened 2023-01-31 05:32 UTC
Ex.

```python
x = 1
match x:
    case 1:
        pass

E999 SyntaxError: invalid syntax. Got unexpected token 'x'
```

when running `ruff --fix` on `v0.0.238` and with `target-version = "py311"` in `pyproject.toml`.

**Comment by messense** [comment] 2023-01-31 05:59
Duplicate of https://github.com/charliermarsh/ruff/issues/282

**Comment by charliermarsh** [comment] 2023-01-31 12:21
Just closing as duplicate.

**Closed by charliermarsh** 2023-01-31 12:21 UTC

**Comment by charliermarsh** [comment] 2023-02-22 00:05
Fixed as of v0.0.250.
