### ISSUE TITLE
Add a new rule to simplify

### ISSUE THREAD

**Issue by JonathanPlasse** [charliermarsh/ruff#2547] opened 2023-02-03 15:57 UTC
I have this code:
```python
def has_permissions(user: User, permissions: list[PermissionEnum]) -> bool:
    for permission in permissions:
        if permission not in user.permissions:
            return False
    return True
```
which was simplified to:
```python
def has_permissions(self, user: User, permissions: list[PermissionEnum]) -> bool:
    return all(not permission not in user.permissions for permission in permissions)
```
but could be simplified further to:
```python
def has_permissions(self, user: User, permissions: list[PermissionEnum]) -> bool:
    return all(permission in user.permissions for permission in permissions)
```
We could detect when we have `not item not in items` and simplify it to `item in items`.

I used `select = ["ALL"]`.

**Comment by charliermarsh** [comment] 2023-02-03 16:26
I think this is a duplicate of #2219 and #2394.

**Closed by charliermarsh** 2023-02-03 16:26 UTC

**Comment by JonathanPlasse** [comment] 2023-02-03 18:33
Sorry for the noise.

**Comment by charliermarsh** [comment] 2023-02-03 18:42
No prob at all.
