### ISSUE TITLE
`PLW3301` auto-fix creates `TypeError`

### ISSUE THREAD

**Issue by janosh** [charliermarsh/ruff#4415] opened 2023-05-13 15:47 UTC
This line raises `PLW3301` (Nested `max` calls can be flattened)

```py
max(1, max([1, 2, 3]))
```

and auto-fixes to

```py
max(1, [1, 2, 3])
```

which raises

> TypeError: '>' not supported between instances of 'list' and 'int'

This seems serious and in need of a hotfix.

**Comment by charliermarsh** [comment] 2023-05-13 15:48
This is a duplicate of #4410 and was fixed by #4412.

**Closed by charliermarsh** 2023-05-13 15:48 UTC
