### ISSUE TITLE
UP034 autofix makes generator code broken

### ISSUE THREAD

**Issue by Olegt0rr** [charliermarsh/ruff#3234] opened 2023-02-26 09:00 UTC
### Code:
```python
the_first_one = next(
    (some_integer for some_integer in range(1000) if some_integer // 2 == 0)
)
```

### Result:
```
0
```

It works.

### Result:

```
UP034 [*] Avoid extraneous parentheses
COM812 [*] Trailing comma missing
```

### Result code:

```python
the_first_one = next(
    some_integer for some_integer in range(1000) if some_integer // 2 == 0,
)
```

### Run code result:

```python
  File "draft.py", line 2
    some_integer for some_integer in range(1000) if some_integer // 2 == 0,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Generator expression must be parenthesized
```

**Comment by matthewlloyd** [comment] 2023-02-26 17:49
Cannot reproduce. Did a different rule autofix, or a formatter like black, add the trailing comma?

```python
$ cat > test.py
the_first_one = next(
    (some_integer for some_integer in range(1000) if some_integer // 2 == 0)
)

$ cargo run --bin ruff check test.py --no-cache --select UP034 --fix
    Finished dev [unoptimized + debuginfo] target(s) in 0.09s
     Running `target/debug/ruff check test.py --no-cache --select UP034 --fix`
Found 1 error (1 fixed, 0 remaining).

$ cat test.py
the_first_one = next(
    some_integer for some_integer in range(1000) if some_integer // 2 == 0
)

$ python3 test.py

$
```

**Comment by charliermarsh** [comment] 2023-02-26 19:12
I think this is a rare case in which applying two independent edits is causing a syntax error. It's fine to add the trailing comma as long as the parentheses are present, and it's fine to remove the parentheses as long as there's no trailing comma, but adding the trailing comma _and_ removing the parentheses is invalid.

**Comment by matthewlloyd** [comment] 2023-02-26 19:40
I tried switching the order of the checks but that doesn't help either. The second check doesn't see the edits made by the first. 

This does seem kind of important - as a user I would want autofixes to never break code. Since I thought about it a bit I'll share some possible solutions, though some are obvious I guess:

* Define a list of groups of mutually incompatible autofixes, to e.g. always disable the UP034 autofix when the COM812 autofix is enabled (not just when it has actually been applied, to preserve idempotence across Ruff runs).
* Divide the autofixable checks into passes (where each pass contains no mutually incompatible autofixes) and rerun the lexer in between each pass if autofixes have been applied.
* Have autofixes mark tokens as being removed, then ignore those tokens in the checkers.
* Have autofixes return a modified LexResult (or modify a mutable one) at the time the diagnostic is created.
* Teach UP034 to ignore situations where COM812 would apply when it's enabled, or vice versa.

**Comment by charliermarsh** [comment] 2023-02-26 19:49
Without addressing the broader issue, one hack we've used in the past is to expand the range of the autofix in some way, such that the fixes have conflicting edit ranges. If the edit ranges conflict, we'll only apply the first of the two fixes in the initial pass. Then, in the second pass, we wouldn't raise the second violation at all (hopefully) and would thus avoid the fix.

**Comment by matthewlloyd** [comment] 2023-02-26 20:05
Ah OK, nice - I didn't see that the linter already runs multiple passes :). That's easy then, and I have a working fix for this. Will submit a PR when I get back to my computer later today.

**Comment by charliermarsh** [comment] 2023-02-26 20:06
Yeah, I don't consider it a "good" solution but it does work.

**Closed** 2023-02-27 03:47 UTC
Labels: bug
