### ISSUE TITLE
Unexpected change in string contents

### ISSUE THREAD

**Issue by sbdchd** [charliermarsh/ruff#3981] opened 2023-04-16 00:26 UTC
not entirely sure which rule is changing it, but for some reason the help text string for a Django ORM column description is being rewritten from using a fancy forward quote: `’` to use a tilde `

```diff
 customer_email = models.CharField(
-    max_length=255, help_text="The customer’s email address."
+    max_length=255, help_text="The customer`s email address."
 )
```

**Comment by dhruvmanila** [comment] 2023-04-16 08:00
Duplicate of #3977

**Closed** 2023-04-16 23:27 UTC
