### ISSUE TITLE
support trailing whitespace (W291) and blank lines contains whitespace (W293)

### ISSUE THREAD

**Issue by kapilt** [charliermarsh/ruff#3008] opened 2023-02-18 12:57 UTC
Hi folks, ruff is great, we just switched a project that was using flake8 over to ruff, its unfortunately still in progress on converting to black (lots of extant prs re spurious conflicts re delay)

one challenge is the lack of whitespace linting, both for trailing and empty lines. I see some previous closed tickets on this but it's also clear it's not been implemented, https://github.com/charliermarsh/ruff/issues/1734  . It would still be super useful to have builtin, I'm fine with skipping the trailing whitespace in multi line strings.

❯ ruff --version
ruff 0.0.24

**Comment by ngnpope** [comment] 2023-02-18 18:01
Duplicate of #2402.

**Comment by charliermarsh** [comment] 2023-02-19 00:39
On the roadmap! But I want to keep tracking these via #2402. (Thank you for trying stuff :))

**Closed by charliermarsh** 2023-02-19 00:39 UTC
